### ISSUE TITLE
Missing rescue?

### ISSUE THREAD

**Issue by ioquatix** [picatz/katacoda-scenarios#1]
https://github.com/picatz/katacoda-scenarios/blob/master/async-ruby/step3.md

Should it have

```ruby
    rescue Async::TimeoutError 
      puts "#{id} timed out!"
```

cc @ur5us

**Comment by picatz** [comment]
@ioquatix Yes it should! 🙈

**Comment by picatz** [comment]
Thank you @ur5us 🙇
